# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdf2222dbdc2dc0ff9866823fed9f9a3d9a6e6bf31dcb2fed59d38e9365b5e1c4c9662fd731cbb24289ebd3009b9a56a478e90ce852b6d086d6017d91a247cf2

test:
  secret_key_base: af60705c12f30054c17ee248a0a3f1bb2187b43d949a3de53c936acb8950203af496d9779113e0b32e1cbad7d8cc6b0d66bad18ba6b4cda912a4ced7e9d43e02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
